# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# freeze strings
Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LeadingCommentSpace:
  Exclude:
    - test/tools/get_docs_test.rb

AllCops:
  Exclude:
    - gemfiles/*
